### PR TITLE
Move Leapp job templates to category 'Leapp'

### PR DESCRIPTION
**Pull request by stejskalleos**

### CODE REVIEW

**Comment by adamruzicka** [comment]
While this is open, shouldn't we change the capitalization of `rhel7`. It doesn't feel right

**Comment by ares** [comment]
Good call, please make it "RHEL 7"

**Comment by stejskalleos** [comment]
rhel7 changed to RHEL 7

**Comment by adamruzicka** [comment]
Thank you @stejskalleos !

**Pull request merged**
