### PR TITLE
Prepare gemspec file for release of 0.0.1

### PR DESCRIPTION
**Pull request by stejskalleos**

### CODE REVIEW

**Comment by adamruzicka** [comment]
Could you rebase to see if the rubocop issues go away?

**Comment by stejskalleos** [comment]
Rebased.

**Comment by stejskalleos** [comment]
Updated:
```
gem build foreman_leapp.gemspec 
  Successfully built RubyGem
  Name: foreman_leapp
  Version: 0.0.1
  File: foreman_leapp-0.0.1.gem
```

**Comment by adamruzicka** [comment]
This plugin currently uses some things from REX which were not released yet. I'll make the release later today and the version will be `3.1.0`, could you adjust the gemspec to depend on that?

**Comment by adamruzicka** [comment]
REX 3.1.0 is out, GH actions are green but travis somehow got stuck. Could you make any change (amend last commit for example) as an attempt to unstuck it?

**Comment by adamruzicka** [comment]
Thank you @stejskalleos !

**Pull request merged**
