### PR TITLE
Set up GitHub actions

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by adamruzicka** [comment]
Not sure why it didn't show up in here, but when it runs it looks like here https://github.com/adamruzicka/foreman_leapp/runs/554752919

**Comment by adamruzicka** [comment]
https://github.com/adamruzicka/foreman_leapp/actions/runs/69009678

**Comment by adamruzicka** [comment]
https://github.com/adamruzicka/foreman_leapp/runs/554946680

**Comment by xprazak2** [comment]
Thanks!

**Pull request merged**
