### PR TITLE
Rename Severity to Risk Factor

### PR DESCRIPTION
**Pull request by stejskalleos**
Issue: https://github.com/oamg/foreman_leapp/issues/91

No changes in code itself, just renaming _Severity_ -> _Risk Factor_ in table header and in the filter dropdown.

### CODE REVIEW

**Comment by xprazak2** [comment]
One nit: it might be good to change the alt for icons as well: https://github.com/oamg/foreman_leapp/blob/master/webpack/components/PreupgradeReportsList/components/helpers.js#L27-L54

**Comment by stejskalleos** [comment]
@xprazak2 Thanks for review, `helpers.js` updated.

**Comment by adamruzicka** [comment]
This made Mr. T unhappy

**Comment by stejskalleos** [comment]
Oh... I forgot about Mr. T. :( Now he's happy again.

**Comment by xprazak2** [comment]
Thanks everyone!

**Pull request merged**
